#!/bin/bash
# /etc/NetworkManager/dispatcher.d/geoblog

IF=$1
STATUS=$2

cd /home/humitos/Source/argentinaenpython.com.ar/web

case "$2" in
    up)
    logger -s "NM Script 'geoblog' triggered"
    /usr/bin/fades --python /usr/bin/python3 /home/humitos/Source/argentinaenpython.com.ar/web/geolocation.py --me & \
    exit 0
    logger -s "NM Script 'geoblog' finished"
    ;;
    *)
    ;;
esac
